version: 2.1

#commands:
#  restore_cache_cmd:
#    steps:
#      - restore_cache:
#          keys:
#            - maven-{{ checksum "pom.xml" }}
#            - maven-
#  save_cache_cmd:
#    steps:
#      - save_cache:
#          key: maven-{{ checksum "pom.xml" }}
#          paths:
#            - ~/.m2
#
#  build:
#    steps:
#      - checkout
#      - restore_cache_cmd
#      - run: ./mvnw -Dmaven.test.skip=true package
#      - save_cache_cmd

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-
      - run: mvn -B -DskipTests clean package
      - save_cache:
          key: maven-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2
      - run:
          name: Test
          command: mvn clean install
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
            - store_test_results:
                path: ~/test-results/junit
            - store_artifacts:
                path: ~/test-results/junit

workflows:
  commit:
    jobs:
      - test
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test