version: 2.1

jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn clean install

workflows:
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *"
          filters:
            branches:
#              only:
#                - master
    jobs:
      - test